// Level: a text file of boxes, camera volumes and triggers. See assets/levels/README.md.
#pragma once
#include "hmath.h"
#include <stdbool.h>

#define LEVEL_MAX_BLOCKS   512
#define LEVEL_MAX_CAMS     64
#define LEVEL_MAX_TRIGGERS 64

// Procedural texture ids, generated by the game at startup. Names in level files match these.
typedef enum TexId { TEX_STONE, TEX_TILE, TEX_WOOD, TEX_METAL, TEX_FLESH, TEX_PLASTER, TEX_COUNT } TexId;

typedef struct Block {
    Vec3 center, size;
    int  tex;        // TexId
    Vec4 tint;       // rgb multiply, a = 1
    float uv_tile;   // texture repeats per world unit; 0 = stretch once
    bool solid;      // blocks the player and boss
} Block;

typedef struct CamVolume {
    char name[32];
    Vec3 vmin, vmax;   // world-space box the player must be inside
    Vec3 eye, target;  // authored camera
    float fov;         // degrees
} CamVolume;

typedef struct Trigger {
    char name[32];
    Vec3 vmin, vmax;
    bool once;
    bool fired;
} Trigger;

typedef struct Level {
    Block     blocks[LEVEL_MAX_BLOCKS];   int nblocks;
    CamVolume cams[LEVEL_MAX_CAMS];       int ncams;
    Trigger   triggers[LEVEL_MAX_TRIGGERS]; int ntriggers;
    Vec3  spawn;      float spawn_yaw;    // player start (yaw in radians)
    Vec3  boss_spawn; float boss_yaw;
    Vec3  arena_min, arena_max;           // fight bounds; the follow camera stays inside
    Vec3  fog_color;  float fog_near, fog_far;
    Vec3  light_dir;  float ambient;  Vec3 light_color;
    char  path[512];
    long long mtime;                      // for hot reload
} Level;

// Parse a level file. Returns false and logs on error; on error *lv is left untouched.
bool level_load(Level *lv, const char *path);
// Reload if the file changed on disk. Returns true if it was reloaded.
bool level_reload_if_changed(Level *lv);
// Move a capsule-ish character (xz circle of radius r, y extent 0..height above pos.y)
// by delta, sliding along solid blocks. Returns the new position. Y is passed through.
Vec3 level_move(const Level *lv, Vec3 pos, float radius, float height, Vec3 delta);
// First camera volume containing p, or NULL.
const CamVolume *level_camera_at(const Level *lv, Vec3 p);
// First trigger containing p that has not fired; marks it fired if once. NULL if none.
Trigger *level_trigger_at(Level *lv, Vec3 p);
// Reset all triggers (used on restart).
void level_reset_triggers(Level *lv);
// Lookup helpers
int level_tex_from_name(const char *name);  // -1 if unknown
