// Level: a text file of boxes, camera volumes and triggers. See assets/levels/README.md.
#pragma once
#include "hmath.h"
#include <stdbool.h>

#define LEVEL_MAX_BLOCKS   512
#define LEVEL_MAX_CAMS     64
#define LEVEL_MAX_TRIGGERS 64
#define LEVEL_MAX_PROPS    2048
#define LEVEL_MAX_LIGHTS   32
#define LEVEL_MAX_EMITTERS 96

// Procedural texture ids, generated by the game at startup. Names in level files match these.
typedef enum TexId { TEX_STONE, TEX_TILE, TEX_WOOD, TEX_METAL, TEX_FLESH, TEX_PLASTER, TEX_FLAT, TEX_COUNT } TexId;

typedef struct Block {
    Vec3 center, size;
    int  tex;        // TexId
    Vec4 tint;       // rgb multiply, a = 1
    float uv_tile;   // texture repeats per world unit; 0 = stretch once
    bool solid;      // blocks the player and boss
} Block;

typedef struct CamVolume {
    char name[32];
    Vec3 vmin, vmax;   // world-space box the player must be inside
    Vec3 eye, target;  // authored camera
    float fov;         // degrees
} CamVolume;

#define LEVEL_MAX_NPCS 12
// npc NAME CHARACTER x y z yaw SCENE [radius]: a character standing in the world; E within radius plays SCENE
typedef struct Npc { char name[32], file[128], scene[128]; Vec3 pos; float yaw, radius; } Npc;

typedef struct Trigger {
    char name[32];
    Vec3 vmin, vmax;
    bool once;
    bool fired;
} Trigger;

typedef struct Prop {
    char  file[128];         // relative to assets/
    Vec3  pos; float yaw, scale; Vec3 stretch;   // stretch: per-axis size multiplier (default 1 1 1)
    Vec4  tint; Vec3 glow;   // glow = emissive colour
    float collide;           // radius of an invisible solid cylinder (0 = none)
} Prop;

typedef struct LevelLight {
    Vec3 pos; Vec3 color; float radius, intensity, flicker;
} LevelLight;

typedef struct LevelEmitter {
    char type[16]; Vec3 pos, extent; float rate; Vec3 color; float size, life;
} LevelEmitter;

// How the overworld is played. `view top` (the default) is the fixed camera from the level's
// `camera` line, `view third` orbits behind the hero with mouse look, `view first` puts the eye
// in the hero's head.
typedef enum ViewMode { VIEW_TOP, VIEW_THIRD, VIEW_FIRST } ViewMode;

// Everything about how a level looks, all optional with sane defaults.
typedef struct Look {
    Vec3 sun_dir; float sun_intensity; Vec3 sun_color;
    Vec3 sky_ambient, ground_ambient;
    Vec3 fog_color; float fog_density, fog_base, fog_falloff, fog_scatter, fog_start;
    Vec3 sky_zenith, sky_horizon, sky_ground; float sun_glow, stars, sky_fog_blend;
    float toon_softness, shadow_floor, rim_power;
    float exposure, saturation, contrast, bloom, bloom_threshold;
    Vec3 lift, gain;
    float pixel_scale, pixel_levels, pixel_outline, pixel_palette, pixel_inner;   // pixel-art character layer (scale 0 = off)
    float shadow;                                                                  // sun shadow strength 0..1 (0 = off)
    float style_snap, style_outline, style_levels, style_pixel;                    // world style layer (post): palette snap, edge ink, colour levels, pixel size
    float cam_pitch, cam_dist, cam_fov, cam_yaw;                                   // overworld camera (degrees, metres, degrees, degrees)
    float daytime;   // hour of the clock 0..24 driving the sun and sky (see daylight.h); negative = use the values above
} Look;

typedef struct Level {
    Prop         props[LEVEL_MAX_PROPS];       int nprops;
    LevelLight   lights[LEVEL_MAX_LIGHTS];     int nlights;
    LevelEmitter emitters[LEVEL_MAX_EMITTERS]; int nemitters;
    Look  look;
    char  scene_intro[128], scene_boss[128], scene_victory[128];   // scene file names under assets/scenes/
    char  terrain_file[128];              // heightmap base name relative to assets/, empty = no terrain
    Block     blocks[LEVEL_MAX_BLOCKS];   int nblocks;
    CamVolume cams[LEVEL_MAX_CAMS];       int ncams;
    Trigger   triggers[LEVEL_MAX_TRIGGERS]; int ntriggers;
    struct { char name[32], file[128]; } scenes[16]; int nscenes;   // scene NAME FILE: a trigger named NAME plays FILE
    bool combat_realtime;   // combat realtime: the boss fight is the third-person action fight instead of the card battle
    ViewMode view;          // view top | third | first (see ViewMode)
    float view_bob;         // first person head bob, 1 = the default subtle amount, 0 = off
    Npc       npcs[LEVEL_MAX_NPCS]; int nnpcs;
    Vec3  spawn;      float spawn_yaw;    // player start (yaw in radians)
    Vec3  boss_spawn; float boss_yaw;
    Vec3  arena_min, arena_max;           // fight bounds; the follow camera stays inside
    Vec3  fog_color;  float fog_near, fog_far;
    Vec3  light_dir;  float ambient;  Vec3 light_color;
    char  path[512];
    long long mtime;                      // for hot reload
} Level;

// Parse a level file. Returns false and logs on error; on error *lv is left untouched.
bool level_load(Level *lv, const char *path);
// Write the level back to disk in the text format level_load reads. Comments in the original file
// are not preserved. Returns false and logs on failure.
bool level_save(const Level *lv, const char *path);
// Reload if the file changed on disk. Returns true if it was reloaded.
bool level_reload_if_changed(Level *lv);
// Move a capsule-ish character (xz circle of radius r, y extent 0..height above pos.y)
// by delta, sliding along solid blocks. Returns the new position. Y is passed through.
Vec3 level_move(const Level *lv, Vec3 pos, float radius, float height, Vec3 delta);
// First camera volume containing p, or NULL.
const CamVolume *level_camera_at(const Level *lv, Vec3 p);
// First trigger containing p that has not fired; marks it fired if once. NULL if none.
Trigger *level_trigger_at(Level *lv, Vec3 p);
// Reset all triggers (used on restart).
void level_reset_triggers(Level *lv);
// Fraction [0,1] along a->b where the segment first enters a solid block grown by margin; 1 if clear.
float level_ray_solid(const Level *lv, Vec3 a, Vec3 b, float margin);
// Lookup helpers
int level_tex_from_name(const char *name);  // -1 if unknown
