// Level: a text file of boxes, camera volumes and triggers. See assets/levels/README.md.
#pragma once
#include "hmath.h"
#include <stdbool.h>

#define LEVEL_MAX_BLOCKS   2048   // parts bring their own colliders, so a wooded level spends these on trunks
#define LEVEL_MAX_CAMS     64
#define LEVEL_MAX_TRIGGERS 64
#define LEVEL_MAX_PROPS    2048
#define LEVEL_MAX_LIGHTS   32
#define LEVEL_MAX_EMITTERS 96

// Procedural texture ids, generated by the game at startup. Names in level files match these.
typedef enum TexId { TEX_STONE, TEX_TILE, TEX_WOOD, TEX_METAL, TEX_FLESH, TEX_PLASTER, TEX_FLAT, TEX_COUNT } TexId;

// Photoscans and other real images drop into assets/textures/ and need no level line of their own:
// every NAME.png|jpg there becomes a texture called NAME, usable anywhere a texture name is taken
// (a `block`'s texture field, a prop's `tex`, a piece's `tex`). The directory is scanned once, on
// first use, and sorted, so an id is the same in every run and survives a save/load round trip.
#define LEVEL_MAX_USER_TEX 48
int         level_user_tex_count(void);
const char *level_user_tex_name(int i);   // "NAME"
const char *level_user_tex_file(int i);   // "textures/NAME.jpg", relative to assets/

typedef struct Block {
    Vec3 center, size;
    int  tex;        // TexId
    Vec4 tint;       // rgb multiply, a = 1
    float uv_tile;   // texture repeats per world unit; 0 = stretch once
    bool solid;      // blocks the player and boss
    bool platform;   // walkable top face that never blocks movement (a prop's `collide R H deck`)
} Block;

typedef struct CamVolume {
    char name[32];
    Vec3 vmin, vmax;   // world-space box the player must be inside
    Vec3 eye, target;  // authored camera
    float fov;         // degrees
} CamVolume;

#define LEVEL_MAX_NPCS 12
// npc NAME CHARACTER x y z yaw SCENE [radius]: a character standing in the world; E within radius plays SCENE
typedef struct Npc { char name[32], file[128], scene[128]; Vec3 pos; float yaw, radius; } Npc;

#define LEVEL_MAX_ITEMS 128
// item NAME x y z [yaw]: a carryable item from assets/items/NAME.txt (see items.h)
typedef struct LevelItem { char name[32]; Vec3 pos; float yaw; } LevelItem;

typedef struct Trigger {
    char name[32];
    Vec3 vmin, vmax;
    bool once;
    bool fired;
} Trigger;

typedef struct Prop {
    char  file[128];         // relative to assets/
    char  name[32];          // `name NAME`: what a cutscene calls it (actor prop:NAME ...); empty = anonymous
    Vec3  pos; float yaw, scale; Vec3 stretch;   // stretch: per-axis size multiplier (default 1 1 1)
    Vec4  tint; Vec3 glow;   // glow = emissive colour
    float collide;           // radius of an invisible solid box at the prop's base (0 = none)
    float collide_h;         // its height in metres (0 = the 5 m default, tall enough to hide behind)
    bool  collide_deck;      // `deck`: the top face is walkable and the box never blocks movement
    bool  collide_default;   // the collider came from the .part's own `collide` line, not this prop line
    int   collide_block;     // index of that block in `blocks`, or -1 (rebuilt on every load)
    int   tex;               // `tex NAME`: one texture over the whole prop; -1 = the model's own textures
    float tex_tile;          // its repeats per metre of world space (default 1), so scale never stretches it
} Prop;

typedef struct LevelLight {
    Vec3 pos; Vec3 color; float radius, intensity, flicker;
} LevelLight;

typedef struct LevelEmitter {
    char type[16]; Vec3 pos, extent; float rate; Vec3 color; float size, life;
} LevelEmitter;

// How the overworld is played. `view top` (the default) is the fixed camera from the level's
// `camera` line, `view third` orbits behind the hero with mouse look, `view first` puts the eye
// in the hero's head.
typedef enum ViewMode { VIEW_TOP, VIEW_THIRD, VIEW_FIRST } ViewMode;

// Everything about how a level looks, all optional with sane defaults.
typedef struct Look {
    Vec3 sun_dir; float sun_intensity; Vec3 sun_color;
    Vec3 sky_ambient, ground_ambient;
    Vec3 fog_color; float fog_density, fog_base, fog_falloff, fog_scatter, fog_start;
    Vec3 sky_zenith, sky_horizon, sky_ground; float sun_glow, stars, sky_fog_blend;
    float toon_softness, shadow_floor, rim_power;
    float exposure, saturation, contrast, bloom, bloom_threshold;
    Vec3 lift, gain;
    float pixel_scale, pixel_levels, pixel_outline, pixel_palette, pixel_inner;   // pixel-art character layer (scale 0 = off)
    float shadow;                                                                  // sun shadow strength 0..1 (0 = off)
    float style_snap, style_outline, style_levels, style_pixel;                    // world style layer (post): palette snap, edge ink, colour levels, pixel size
    float cam_pitch, cam_dist, cam_fov, cam_yaw;                                   // overworld camera (degrees, metres, degrees, degrees)
    float daytime;   // hour of the clock 0..24 driving the sun and sky (see daylight.h); negative = use the values above
    float view_far;  // camera far plane in metres (`look far F`); 80 is the village default, ~600 for a 300 m island

    // The three candidate art directions, all off by default (see assets/looks/README.md).
    float render_scale;    // internal render resolution, 1 = full (1280x800), 0.5 = 640x400 upscaled
    float render_nearest;  // 1 = upscale that low-res frame with nearest neighbour, 0 = bilinear
    float tex_cap;         // cap every texture's longest edge at this many pixels (0 = engine default)
    float flat;            // 0..1 blend every material toward its texture's mean colour
    float grain, vignette; // film grain amount and vignette strength (grain 0 and vignette 0.45 are the old hardcoded values)
    float chroma;          // chromatic aberration at the frame's corners, in pixels
    float dither;          // ordered 4x4 dither added before the `style` colour crunch
    float ink_width;       // ink line width in pixels (1 = the old one-pixel depth ink)
    float ink_wobble;      // ink sample wobble in pixels, stepped at 8 Hz, so lines "boil"
    float ink_luma;        // 0..1 weight of a luminance edge added to the depth edge (interior creases)
    float hatch;           // 0..1 screen-space hatching where the frame is already dark
    float paper;           // 0..1 paper texture multiplied over the frame
} Look;

typedef struct Level {
    Prop         props[LEVEL_MAX_PROPS];       int nprops;
    LevelLight   lights[LEVEL_MAX_LIGHTS];     int nlights;
    LevelEmitter emitters[LEVEL_MAX_EMITTERS]; int nemitters;
    Look  look;
    char  scene_intro[128], scene_boss[128], scene_victory[128];   // scene file names under assets/scenes/
    char  terrain_file[128];              // heightmap base name relative to assets/, empty = no terrain
    Block     blocks[LEVEL_MAX_BLOCKS];   int nblocks;
    CamVolume cams[LEVEL_MAX_CAMS];       int ncams;
    Trigger   triggers[LEVEL_MAX_TRIGGERS]; int ntriggers;
    struct { char name[32], file[128]; } scenes[16]; int nscenes;   // scene NAME FILE: a trigger named NAME plays FILE
    bool combat_realtime;   // combat realtime: the boss fight is the third-person action fight instead of the card battle
    ViewMode view;          // view top | third | first (see ViewMode)
    float view_bob;         // first person head bob, 1 = the default subtle amount, 0 = off
    Npc       npcs[LEVEL_MAX_NPCS]; int nnpcs;
    LevelItem items[LEVEL_MAX_ITEMS]; int nitems;
    Vec3  spawn;      float spawn_yaw;    // player start (yaw in radians)
    Vec3  boss_spawn; float boss_yaw;
    Vec3  arena_min, arena_max;           // fight bounds; the follow camera stays inside
    Vec3  fog_color;  float fog_near, fog_far;
    Vec3  light_dir;  float ambient;  Vec3 light_color;
    char  path[512];
    long long mtime;                      // for hot reload
} Level;

// Parse a level file. Returns false and logs on error; on error *lv is left untouched.
bool level_load(Level *lv, const char *path);
void level_look_include(Level *lv, const char *name);   // apply assets/looks/NAME.txt over an already-loaded level (HOLLOW_LOOK)
// Write the level back to disk in the text format level_load reads. Comments in the original file
// are not preserved. Returns false and logs on failure.
bool level_save(const Level *lv, const char *path);
// Reload if the file changed on disk. Returns true if it was reloaded.
bool level_reload_if_changed(Level *lv);
// How high a character steps up without jumping. Also the height a block has to exceed before it
// blocks movement at all: anything shorter is a step, not a wall.
#define LEVEL_STEP_UP 0.5f

// Highest walkable surface under `pos` that is no more than LEVEL_STEP_UP above its feet, starting
// from `base` (the terrain, or 0 on a level without one). Solid blocks and decks both hold a
// character up; only the xz centre is tested. *block, if given, receives the block index that won,
// or -1 for `base` itself.
float level_ground(const Level *lv, Vec3 pos, float base, int *block);

// Move a capsule-ish character (xz circle of radius r, y extent 0..height above pos.y)
// by delta, sliding along solid blocks. Returns the new position. Y is passed through.
Vec3 level_move(const Level *lv, Vec3 pos, float radius, float height, Vec3 delta);

// --- traversal --- level_ground answers "what am I standing on", which is a question about a step.
// Climbing something is a different question: what is the top of the thing in my way, is there room
// to stand on it, and which way does its face point. These three answer that, and no level markup
// is involved -- a ledge is any block top, deck or hillside of the right height.
//
// Highest solid or platform top in this column at or below `ceiling`; -1e9f when the column is
// empty. Unlike level_ground there is no step limit: that is the caller's decision to make.
float level_top_at(const Level *lv, float x, float z, float ceiling, int *block);
// Is there room for a circle of `radius` at (x, z) spanning y0..y1? Decks never block anything, so
// only `solid` blocks count -- the same rule move_axis plays by, minus its step-up exemption.
bool  level_clear(const Level *lv, float x, float z, float radius, float y0, float y1);
// The horizontal normal of the nearest solid face within `radius` of (x, z) over y0..y1, pointing
// away from the wall, with the gap to it. False when there is no wall in reach.
bool  level_wall_near(const Level *lv, float x, float z, float radius, float y0, float y1, Vec3 *normal, float *gap);
// First camera volume containing p, or NULL.
const CamVolume *level_camera_at(const Level *lv, Vec3 p);
// First trigger containing p that has not fired; marks it fired if once. NULL if none.
Trigger *level_trigger_at(Level *lv, Vec3 p);
// The trigger volume with this name, or NULL. Unlike level_trigger_at this never fires it:
// it is for volumes used as a query (the boat's cargo `hold`).
const Trigger *level_trigger_named(const Level *lv, const char *name);
// Reset all triggers (used on restart).
void level_reset_triggers(Level *lv);
// Fraction [0,1] along a->b where the segment first enters a solid block grown by margin; 1 if clear.
float level_ray_solid(const Level *lv, Vec3 a, Vec3 b, float margin);
// Lookup helpers
int level_tex_from_name(const char *name);  // -1 if unknown
const char *level_tex_name(int id);         // "stone".."flat" or a scanned NAME; "flat" if out of range
