// Terrain file layer: heights as a 16-bit-in-8-bit-RGBA PNG, colours as an 8-bit RGBA PNG,
// plus a tiny text sidecar for cell size and origin. See terrain.h.
#include "terrain.h"
#include "vendor/stb_image.h"
#include "vendor/stb_image_write.h"
#include <SDL3/SDL.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Height range packed into the 16-bit heightmap: h in [-64, 192) maps onto [0, 65535].
#define TERRAIN_H_MIN   -64.0f
#define TERRAIN_H_RANGE 256.0f

static uint16_t encode_height(float h) {
    float t = (h - TERRAIN_H_MIN) / TERRAIN_H_RANGE * 65535.0f;
    return (uint16_t)clampf(t + 0.5f, 0.0f, 65535.0f);
}

static float decode_height(uint16_t v) {
    return (float)v / 65535.0f * TERRAIN_H_RANGE + TERRAIN_H_MIN;
}

bool terrain_save(const Terrain *t, const char *asset_dir) {
    const int n = TERRAIN_N;
    uint8_t *hbuf = malloc((size_t)n * (size_t)n * 4);
    uint8_t *cbuf = malloc((size_t)n * (size_t)n * 4);
    if (!hbuf || !cbuf) {
        free(hbuf); free(cbuf);
        SDL_LogError(SDL_LOG_CATEGORY_APPLICATION, "terrain_save: out of memory");
        return false;
    }

    for (int i = 0; i < n * n; i++) {
        uint16_t v = encode_height(t->height[i]);
        hbuf[i * 4 + 0] = (uint8_t)(v >> 8);
        hbuf[i * 4 + 1] = (uint8_t)(v & 0xFF);
        hbuf[i * 4 + 2] = 0;
        hbuf[i * 4 + 3] = 255;

        Vec3 c = t->color[i];
        cbuf[i * 4 + 0] = (uint8_t)(clampf(c.x, 0.0f, 1.0f) * 255.0f + 0.5f);
        cbuf[i * 4 + 1] = (uint8_t)(clampf(c.y, 0.0f, 1.0f) * 255.0f + 0.5f);
        cbuf[i * 4 + 2] = (uint8_t)(clampf(c.z, 0.0f, 1.0f) * 255.0f + 0.5f);
        cbuf[i * 4 + 3] = 255;
    }

    char hpath[768], cpath[768], tpath[768];
    snprintf(hpath, sizeof hpath, "%s/%s_h.png", asset_dir, t->file);
    snprintf(cpath, sizeof cpath, "%s/%s_c.png", asset_dir, t->file);
    snprintf(tpath, sizeof tpath, "%s/%s.txt", asset_dir, t->file);

    bool ok = stbi_write_png(hpath, n, n, 4, hbuf, n * 4) != 0;
    ok = ok && stbi_write_png(cpath, n, n, 4, cbuf, n * 4) != 0;
    free(hbuf);
    free(cbuf);
    if (!ok) {
        SDL_LogError(SDL_LOG_CATEGORY_APPLICATION, "terrain_save: failed to write %s / %s", hpath, cpath);
        return false;
    }

    FILE *f = fopen(tpath, "w");
    if (!f) { SDL_LogError(SDL_LOG_CATEGORY_APPLICATION, "terrain_save: failed to write %s", tpath); return false; }
    fprintf(f, "# generated by the terrain editor\n");
    fprintf(f, "cell %g\n", (double)t->cell);
    fprintf(f, "origin %g %g %g\n", (double)t->origin.x, (double)t->origin.y, (double)t->origin.z);
    bool wok = (fclose(f) == 0);
    if (!wok) SDL_LogError(SDL_LOG_CATEGORY_APPLICATION, "terrain_save: error writing %s", tpath);
    return wok;
}

// Read `cell` and `origin` out of the sidecar text file; defaults if the file is missing or a
// line is absent. Unknown lines and comments (#) are ignored.
static void load_sidecar(const char *tpath, float *cell, Vec3 *origin) {
    *cell = 1.5f;
    *origin = v3(-96.0f, 0.0f, -96.0f);

    size_t size = 0;
    void *data = SDL_LoadFile(tpath, &size);
    if (!data) return;

    char *buf = malloc(size + 1);
    if (!buf) { SDL_free(data); return; }
    memcpy(buf, data, size);
    buf[size] = '\0';
    SDL_free(data);

    char *save = NULL;
    for (char *line = SDL_strtok_r(buf, "\n", &save); line; line = SDL_strtok_r(NULL, "\n", &save)) {
        char *hash = strchr(line, '#');
        if (hash) *hash = '\0';
        char key[32];
        float f[3];
        int got = sscanf(line, "%31s %f %f %f", key, &f[0], &f[1], &f[2]);
        if (got < 2) continue;
        if (strcmp(key, "cell") == 0) *cell = f[0];
        else if (strcmp(key, "origin") == 0 && got == 4) *origin = v3(f[0], f[1], f[2]);
    }
    free(buf);
}

bool terrain_load(Terrain *t, const char *asset_dir, const char *file) {
    char hpath[768], cpath[768], tpath[768];
    snprintf(hpath, sizeof hpath, "%s/%s_h.png", asset_dir, file);
    snprintf(cpath, sizeof cpath, "%s/%s_c.png", asset_dir, file);
    snprintf(tpath, sizeof tpath, "%s/%s.txt", asset_dir, file);

    int hw, hh, hn;
    uint8_t *hbuf = stbi_load(hpath, &hw, &hh, &hn, 4);
    if (!hbuf) {
        SDL_LogError(SDL_LOG_CATEGORY_APPLICATION, "terrain_load: cannot decode %s", hpath);
        return false;
    }
    if (hw != TERRAIN_N || hh != TERRAIN_N) {
        SDL_LogError(SDL_LOG_CATEGORY_APPLICATION, "terrain_load: %s is %dx%d, expected %dx%d",
                     hpath, hw, hh, TERRAIN_N, TERRAIN_N);
        stbi_image_free(hbuf);
        return false;
    }

    int cw, ch, cn;
    uint8_t *cbuf = stbi_load(cpath, &cw, &ch, &cn, 4);
    bool have_color = cbuf && cw == TERRAIN_N && ch == TERRAIN_N;
    if (cbuf && !have_color) {
        SDL_LogWarn(SDL_LOG_CATEGORY_APPLICATION, "terrain_load: %s is %dx%d, expected %dx%d, ignoring",
                    cpath, cw, ch, TERRAIN_N, TERRAIN_N);
    }

    float cell;
    Vec3 origin;
    load_sidecar(tpath, &cell, &origin);

    Terrain tmp;
    memset(&tmp, 0, sizeof tmp);
    tmp.cell = cell;
    tmp.origin = origin;
    for (int i = 0; i < TERRAIN_N * TERRAIN_N; i++) {
        uint16_t v = (uint16_t)((hbuf[i * 4 + 0] << 8) | hbuf[i * 4 + 1]);
        tmp.height[i] = decode_height(v);
        tmp.color[i] = have_color
            ? v3(cbuf[i * 4 + 0] / 255.0f, cbuf[i * 4 + 1] / 255.0f, cbuf[i * 4 + 2] / 255.0f)
            : v3(0.3f, 0.5f, 0.2f);
    }
    stbi_image_free(hbuf);
    if (cbuf) stbi_image_free(cbuf);

    tmp.present = true;
    SDL_strlcpy(tmp.file, file, sizeof tmp.file);
    tmp.mesh_dirty = true;
    tmp.mesh_ok = false;

    *t = tmp;
    return true;
}
